TYPO3:
  Neos:
    typoScript:
      autoInclude:
        Flownative.Anchorlinks: true
    userInterface:
      translation:
        autoInclude:
          'Flownative.Anchorlinks': ['Main', 'NodeTypes/*']
      requireJsPathMapping:
        'Flownative.Anchorlinks/Views': 'resource://Flownative.Anchorlinks/Public/JavaScript/Inspector/Views'
