TYPO3:
  Neos:
    typoScript:
      autoInclude:
        Dimaip.Anchor: true
    userInterface:
      translation:
        autoInclude:
          'Dimaip.Anchor': ['Main', 'NodeTypes/*']
      requireJsPathMapping:
        'Dimaip.Anchor/Views': 'resource://Dimaip.Anchor/Public/JavaScript/Inspector/Views'
